$ipc = qs -c noctalia-shell ipc call

general {
  lock_cmd = $ipc lockScreen lock
  before_sleep_cmd = $ipc lockScreen lock
}

listener {
  timeout = 300
  on-timeout = $ipc lockScreen lock
}

listener {
  timeout = 330
  on-timeout = hyprctl dispatch dpms off
  on-resume  = hyprctl dispatch dpms on
}
