source = ~/.config/hypr/settings/variables.conf
source = ~/.config/hypr/settings/inputs.conf
source = ~/.config/hypr/settings/misc.conf
source = ~/.config/hypr/settings/general.conf
source = ~/.config/hypr/noctalia/noctalia-colors.conf
source = ~/.config/hypr/settings/bindings.conf
source = ~/.config/hypr/settings/executions.conf
