# Misc settings
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 0
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    layers_hog_keyboard_focus = true
    focus_on_activate = false
    mouse_move_focuses_monitor = true
}
